// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// adjacencyCpp
IntegerMatrix adjacencyCpp(const IntegerMatrix& ls_pairs, const List& nodes, const List& ls_node_map);
RcppExport SEXP _TDAmapper_adjacencyCpp(SEXP ls_pairsSEXP, SEXP nodesSEXP, SEXP ls_node_mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type ls_pairs(ls_pairsSEXP);
    Rcpp::traits::input_parameter< const List& >::type nodes(nodesSEXP);
    Rcpp::traits::input_parameter< const List& >::type ls_node_map(ls_node_mapSEXP);
    rcpp_result_gen = Rcpp::wrap(adjacencyCpp(ls_pairs, nodes, ls_node_map));
    return rcpp_result_gen;
END_RCPP
}
// constructLevelSets
List constructLevelSets(const NumericMatrix& filter_values, const IntegerMatrix& index_set, const NumericVector& interval_length, const NumericVector& step_size, const NumericVector& filter_min);
RcppExport SEXP _TDAmapper_constructLevelSets(SEXP filter_valuesSEXP, SEXP index_setSEXP, SEXP interval_lengthSEXP, SEXP step_sizeSEXP, SEXP filter_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type filter_values(filter_valuesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type index_set(index_setSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type interval_length(interval_lengthSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type filter_min(filter_minSEXP);
    rcpp_result_gen = Rcpp::wrap(constructLevelSets(filter_values, index_set, interval_length, step_size, filter_min));
    return rcpp_result_gen;
END_RCPP
}
// dist_subset
NumericVector dist_subset(const NumericVector& dist, IntegerVector idx);
RcppExport SEXP _TDAmapper_dist_subset(SEXP distSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_subset(dist, idx));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TDAmapper_adjacencyCpp", (DL_FUNC) &_TDAmapper_adjacencyCpp, 3},
    {"_TDAmapper_constructLevelSets", (DL_FUNC) &_TDAmapper_constructLevelSets, 5},
    {"_TDAmapper_dist_subset", (DL_FUNC) &_TDAmapper_dist_subset, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_TDAmapper(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
