# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adjacencyCpp <- function(ls_pairs, nodes, ls_node_map) {
    .Call('_TDAmapper_adjacencyCpp', PACKAGE = 'TDAmapper', ls_pairs, nodes, ls_node_map)
}

constructLevelSets <- function(filter_values, index_set, interval_length, step_size, filter_min) {
    .Call('_TDAmapper_constructLevelSets', PACKAGE = 'TDAmapper', filter_values, index_set, interval_length, step_size, filter_min)
}

dist_subset <- function(dist, idx) {
    .Call('_TDAmapper_dist_subset', PACKAGE = 'TDAmapper', dist, idx)
}

